= Asciidoctor Activities at Write the Docs Portland 2019
:idprefix:
:idseparator: -
:repo
ifndef::env-github[:icons: font]
ifdef::env-github,env-browser[]
:toc: macro
:toclevels: 1
endif::[]
ifdef::env-github[]
:!toc-title:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

This repository/project facilitates planning for and participation in Asciidoctor-related “programming” at Write the Docs 2019.
Asciidoctor is an official sponsor of Writing Day 2019 (Sunday, 19 May), but all of the activities discussed here are officially part of WTD 2019.

We are a group of <<who,AsciiDoc aficionados/evangelists>> eager to share our open-source ways with everyone who loves creating great technical documentation.
These are some ways we hope to enhance the WTD 2019 experience for ourselves and other participants.

toc::[]

[[writing-day]]
== Writing Day

Asciidoctor is a proud sponsor of link:https://www.writethedocs.org/conf/portland/2019/writing-day/[WTD Writing Day 2019].
As a nonprofit open-source provider, Asciidoctor will have a strong presence throughout the conference.
On Writing Day, volunteers will offer tutorials and workshops on common sticking points, from setting up an environment to working with Git to deploying a site sourced in AsciiDoc and generated by Antora or Jekyll.
Writing Day Activities are being planned under the link:https://github.com/DocOps/wtd2019/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22writing+day+2019%22+label%3Aworkshop%2Fsession+[*Writing Day 2019* and *session* issues tags].

[[lightning-talks]]
== Lightning Talks

We should not nominate more than one Asciidoctor-specific Lightning talk, if that; and we should accept that the committee might reject it on the basis that it might look like favoritism.
But we certainly have learned countless lessons in our years doing docs-as-code that are not exactly “on-brand”.

Recommendations for 5-minute, general-audience lessons go under the link:https://github.com/DocOps/wtd2019/issues/2[Lightning Talks Brainstorm issue].

[[unconference]]
== Unconference Sessions

These are 30-minute roundtables, usually very informal.
They can give a topic a deep dive, involving discussion or demos.
There's no telling how many people will show up, but we can print up some logo-emblazoned cards to make them stand out.

Suggestions for and discussion of link:https://www.writethedocs.org/conf/portland/2019/unconference/[Unconference] session topics goes under the link:https://github.com/DocOps/wtd2019/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3Aunconference+label%3Asession[*unconference* and *session* labels].

[[contributor-flow]]
== Participant Contributions and Workflow

We intend to offer link:https://github.com/DocOps/wtd2019[_this repo and GitHub project space_] as a playground for the whole WTD2019/Asciidoctor experience.
Participants in our Writing Day programming will be able to branch or fork this repo and issue merge requests with new content.

[[who]]
== Who We Are

This project was kicked off by members of the teams behind link:https://asciidoctor.org/[Asciidoctor], link:https://antora.org/[Antora], and link:https://github.com/docops/liquidoc-gem[LiquiDoc] -- fully open-source tools intended to make the AsciiDoc markup language more powerful and accessible.
If you want to get involved, link:https://github.com/DocOps/wtd2019/issues/3[let us know how!]

[[license]]
== License

This repository is maintained collaboratively by link:https://opendevise.com/[OpenDevise], link:http://codewriting.org/codewriter-brian-dominick[Codewriting], and other contributors, released like the rest of our toolchain, under link:[The MIT License].
